id: P000800
initial_creation_type: ocr
created_at: 11/03/2021
last_modified_at: 2021-12-17 10:11:15.658218
source_metadata:
  id: bdr:W23703
  title: བསྟན་འགྱུར ༼སྡེ་དགེ༽
  volumes: ''
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
